spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/boot_rights_mannger?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    
server:
  port: 8080
  
#mappers 多个接口时逗号隔开
mapper:
  mappers: cn.mapper.common.MyMapper
  not-empty: false
  identity: MYSQL
  order: after

thymeleaf:
   cache: false


mybatis:
  config-location: classpath:config/mybatis-config.xml
# type-aliases扫描路径
  type-aliases-package: com.xxd.pojo
# mapper xml实现扫描路径
  mapper-locations: classpath:mapper/system/*.xml  
  property:
    order: BEFORE
  
#pagehelper
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
